import Foundation

/// Renders the files Scope projects into a task root (spec §4.6): `AGENTS.md` and the
/// `<slug>.code-workspace` multi-root file. Pure functions, testable without git.
public enum TaskProjection {
    /// Marker on the first line of a generated `AGENTS.md`, so a user-authored file is recognisable.
    public static let generatedMarker = "<!-- generated by Scope; edits are overwritten when the task changes -->"

    /// `AGENTS.md` content.
    ///
    /// - Parameters:
    ///   - task: the task; its active repos are listed with their sandbox paths.
    ///   - otherRepos: relative paths of the scope's other repos (names only until the Graph lands in M3).
    ///   - scopeName: display name of the scope.
    public static func agentsMarkdown(task: TaskRecord, otherRepos: [String], scopeName: String) -> String {
        var lines: [String] = [generatedMarker, "# Task: \(task.name)", ""]
        lines.append("- Scope: \(scopeName)")
        lines.append("- Branch: `\(task.branch)`")
        lines.append("- Task root: `\(task.root)`")
        lines.append("")
        lines.append("## Repositories of this task")
        lines.append("")
        let active = task.activeRepos
        if active.isEmpty {
            lines.append("_No repository yet._")
        }
        for repo in active {
            let name = repo.isScopeRoot ? scopeName : repo.repoRelativePath
            lines.append("- **\(name)** — sandbox: `\(repo.sandboxPath)` (branch `\(repo.branch)`)")
        }
        lines.append("")
        let others = otherRepos.filter { path in !active.contains { $0.repoRelativePath == path } }.sorted()
        if !others.isEmpty {
            lines.append("## Other repositories of the scope")
            lines.append("")
            lines.append("Not part of this task. Ask before adding one to the task.")
            lines.append("")
            for path in others { lines.append("- \(path)") }
            lines.append("")
        }
        lines.append("## Rules")
        lines.append("")
        lines.append("- Work only inside the sandboxes listed above.")
        lines.append("- Never modify the base checkouts under `\(task.scopeRoot)`.")
        lines.append("- Stay on branch `\(task.branch)`; do not switch branches or create new ones.")
        lines.append("- Commit as you go; the user reviews and pushes from Scope.")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    /// `<slug>.code-workspace` content: one folder per active sandbox, named after the repo.
    public static func workspaceJSON(task: TaskRecord) throws -> Data {
        struct Folder: Encodable { let name: String; let path: String }
        struct Workspace: Encodable { let folders: [Folder]; let settings: [String: String] }
        let folders = task.activeRepos.map { repo in
            Folder(name: repo.isScopeRoot ? task.slug : repo.repoRelativePath,
                   path: repo.isScopeRoot ? "." : repo.repoRelativePath)
        }
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        return try encoder.encode(Workspace(folders: folders, settings: [:]))
    }
}
